on:
  push:
    branches:
      - harbor-build
    paths:
      - '**/*.sh'
      - '**/*.xml'
      - '.github/workflows/test.yml'
      - '.github/workflows/check.yml'
      - 'Dockerfile'

name: "Test"
permissions: {}

jobs:
  shellcheck:
    name: Test
    uses: ./.github/workflows/check.yml
